export { resolveKey, resolveAll } from "./resolver";
export { coerce, validateSchema } from "./schema";
export { parseEnvFile, loadLayers } from "./loader";
export { resolveRef, interpolate, interpolateAll } from "./interpolate";
export { mergeLayers, mergeTwo, pickKeys, omitKeys } from "./merge";
export { buildLayerStack, createLayer } from "./priority";
export { applyTransform, applyTransforms } from "./transform";
export { watchEnvFiles } from "./watch";
export { takeSnapshot, diffSnapshots } from "./snapshot";
export { isSensitive, maskValue, maskEnv, maskKeys, getSensitiveKeys } from "./mask";
export { recordEvent, getAuditLog, clearAuditLog, filterAuditLog, auditSummary } from "./audit";
export { encryptValue, decryptValue, encryptEnv, decryptEnv } from "./encrypt";
export { shouldRedact, redactValue, redactEnv, redactKeys } from "./redact";
export { cacheSet, cacheGet, cacheHas, cacheDelete, cacheClear } from "./cache";
export { validateEnv, assertEnv } from "./validate";
export { defineDefaults, applyDefaults, mergeDefaults, resolvedDefaultKeys } from "./defaults";
export { freezeEnv, isFrozen, assertMutable, thawEnv, extendFrozen } from "./freeze";
export type { FrozenEnv } from "./freeze";
